package usecase

import (
	"context"

	"github.com/gymbot/workout-tracker-back/internal/application/dto"
	"github.com/gymbot/workout-tracker-back/internal/domain/repository"
	"github.com/gymbot/workout-tracker-back/pkg/apperror"
)

// RenewUpdateProfileUseCase handles updating user preferences and triggering routine regeneration
type RenewUpdateProfileUseCase struct {
	planRepo           repository.PlanRepository
	scheduleRepo       repository.ScheduleWriter
	workoutRenewalRepo repository.WorkoutRenewalWriter
	profileRepo        repository.ProfileRepository
}

// NewRenewUpdateProfileUseCase creates a new RenewUpdateProfileUseCase
func NewRenewUpdateProfileUseCase(
	planRepo repository.PlanRepository,
	scheduleRepo repository.ScheduleWriter,
	workoutRenewalRepo repository.WorkoutRenewalWriter,
	profileRepo repository.ProfileRepository,
) *RenewUpdateProfileUseCase {
	return &RenewUpdateProfileUseCase{
		planRepo:           planRepo,
		scheduleRepo:       scheduleRepo,
		workoutRenewalRepo: workoutRenewalRepo,
		profileRepo:        profileRepo,
	}
}

// Execute updates user profile preferences, clears workouts and schedule,
// and increments the mesocycle. The n8n workflow will then call GymRatForm
// to regenerate the routine based on the updated profile.
func (uc *RenewUpdateProfileUseCase) Execute(
	ctx context.Context,
	userID string,
	req *dto.UpdateProfileRequest,
) (*dto.UpdateProfileResponse, error) {
	if userID == "" {
		return nil, apperror.NewValidationError("user_id is required")
	}

	// 1. Verify mesocycle is complete
	status, err := uc.planRepo.GetMesocycleStatus(ctx, userID)
	if err != nil {
		return nil, err
	}

	if status == nil {
		return nil, apperror.NewNotFoundError("no active plan found for user")
	}

	if !status.IsComplete {
		return nil, apperror.NewValidationError("mesocycle is not yet complete")
	}

	// 2. Get user profile to find WhatsApp ID
	profile, err := uc.profileRepo.GetByUserID(ctx, userID)
	if err != nil {
		return nil, err
	}

	if profile == nil {
		return nil, apperror.NewNotFoundError("user profile not found")
	}

	// 3. Update profile preferences if provided
	profileUpdated := false
	if req != nil && (req.PriorityMuscles != nil || req.HealthStatus != nil || req.SessionDuration != nil) {
		priorityMuscles := ""
		healthStatus := ""
		sessionDuration := ""

		if req.PriorityMuscles != nil {
			priorityMuscles = *req.PriorityMuscles
		}
		if req.HealthStatus != nil {
			healthStatus = *req.HealthStatus
		}
		if req.SessionDuration != nil {
			sessionDuration = *req.SessionDuration
		}

		if err := uc.profileRepo.UpdatePreferences(ctx, profile.WhatsAppID, priorityMuscles, healthStatus, sessionDuration); err != nil {
			return nil, apperror.NewInternalError("failed to update profile preferences", err)
		}
		profileUpdated = true
	}

	// 4. Clear schedule
	if err := uc.scheduleRepo.ClearSchedule(ctx, userID); err != nil {
		return nil, apperror.NewInternalError("failed to clear schedule", err)
	}

	// 5. Delete all workouts (will be regenerated by GymRatForm)
	if err := uc.workoutRenewalRepo.DeleteUserWorkouts(ctx, userID); err != nil {
		return nil, apperror.NewInternalError("failed to delete workouts", err)
	}

	// 6. Increment mesocycle
	if err := uc.planRepo.IncrementMesocycle(ctx, userID); err != nil {
		return nil, apperror.NewInternalError("failed to increment mesocycle", err)
	}

	return &dto.UpdateProfileResponse{
		Success:              true,
		Message:              "Tu perfil ha sido actualizado. Se generara una nueva rutina personalizada.",
		NewMesocycleNumber:   status.MesocycleNumber + 1,
		RequiresRegeneration: true,
		ProfileUpdated:       profileUpdated,
		WorkoutsDeleted:      true,
		ScheduleCleared:      true,
	}, nil
}
