package usecase

import (
	"context"
	"strconv"

	"github.com/gymbot/workout-tracker-back/internal/application/dto"
	"github.com/gymbot/workout-tracker-back/internal/domain/repository"
	"github.com/gymbot/workout-tracker-back/pkg/apperror"
)

// WeekScheduleMapping maps days per week to schedule type
// Note: database has ul_4 (upper/lower), not ua_4
var WeekScheduleMapping = map[int]string{
	2: "fb_2",  // Full body 2 days
	3: "fb_3",  // Full body 3 days
	4: "ul_4",  // Upper/Lower 4 days
	5: "ppl_5", // Push/Pull/Legs 5 days
	6: "ppl_6", // Push/Pull/Legs 6 days
}

// RenewChangeDaysUseCase handles changing training frequency
type RenewChangeDaysUseCase struct {
	planRepo           repository.PlanRepository
	scheduleRepo       repository.ScheduleWriter
	workoutRenewalRepo repository.WorkoutRenewalWriter
}

// NewRenewChangeDaysUseCase creates a new RenewChangeDaysUseCase
func NewRenewChangeDaysUseCase(
	planRepo repository.PlanRepository,
	scheduleRepo repository.ScheduleWriter,
	workoutRenewalRepo repository.WorkoutRenewalWriter,
) *RenewChangeDaysUseCase {
	return &RenewChangeDaysUseCase{
		planRepo:           planRepo,
		scheduleRepo:       scheduleRepo,
		workoutRenewalRepo: workoutRenewalRepo,
	}
}

// Execute changes the training frequency for the next mesocycle
func (uc *RenewChangeDaysUseCase) Execute(
	ctx context.Context,
	userID string,
	req *dto.RenewChangeDaysRequest,
) (*dto.ChangeDaysResponse, error) {
	if userID == "" {
		return nil, apperror.NewValidationError("user_id is required")
	}

	if req == nil {
		return nil, apperror.NewValidationError("request is required")
	}

	if err := req.Validate(); err != nil {
		return nil, apperror.NewValidationError(err.Error())
	}

	// 1. Verify mesocycle is complete
	status, err := uc.planRepo.GetMesocycleStatus(ctx, userID)
	if err != nil {
		return nil, err
	}

	if status == nil {
		return nil, apperror.NewNotFoundError("no active plan found for user")
	}

	if !status.IsComplete {
		return nil, apperror.NewValidationError("mesocycle is not yet complete")
	}

	// 2. Get new week schedule type
	newWeekSchedule, exists := WeekScheduleMapping[req.NewDaysPerWeek]
	if !exists {
		return nil, apperror.NewValidationError("invalid days per week")
	}

	oldDaysPerWeek := status.DaysPerWeek
	requiresRegeneration := oldDaysPerWeek != req.NewDaysPerWeek

	// 3. Clear schedule
	if err := uc.scheduleRepo.ClearSchedule(ctx, userID); err != nil {
		return nil, apperror.NewInternalError("failed to clear schedule", err)
	}

	// 4. Delete workouts if frequency changed (will be regenerated by GymRatForm)
	if requiresRegeneration {
		if err := uc.workoutRenewalRepo.DeleteUserWorkouts(ctx, userID); err != nil {
			return nil, apperror.NewInternalError("failed to delete workouts", err)
		}
	}

	// 5. Update week schedule in plan
	if err := uc.planRepo.UpdateWeekSchedule(ctx, userID, newWeekSchedule); err != nil {
		return nil, apperror.NewInternalError("failed to update week schedule", err)
	}

	// 6. Increment mesocycle
	if err := uc.planRepo.IncrementMesocycle(ctx, userID); err != nil {
		return nil, apperror.NewInternalError("failed to increment mesocycle", err)
	}

	message := "Tu frecuencia de entrenamiento ha sido actualizada."
	if requiresRegeneration {
		message += " Se generara una nueva rutina con " + strconv.Itoa(req.NewDaysPerWeek) + " dias."
	}

	return &dto.ChangeDaysResponse{
		RenewalResponse: dto.RenewalResponse{
			Success:            true,
			RenewalType:        "CAMBIAR_DIAS",
			NewMesocycleNumber: status.MesocycleNumber + 1,
			Message:            message,
			ScheduleCleared:    true,
			NewWeekSchedule:    newWeekSchedule,
		},
		OldDaysPerWeek:       oldDaysPerWeek,
		NewDaysPerWeek:       req.NewDaysPerWeek,
		RequiresRegeneration: requiresRegeneration,
	}, nil
}
